### ISSUE TITLE
Update maven repository

### ISSUE THREAD

**Issue by kfjohnny2** [devsideal/VectorChildFinder#6]
Hello, I've noticed that the line 1513 on this code is different from the actual class on maven repository, that is declarated as private.

**Comment by devsideal** [comment]
Make sure your import should like- `import com.devs.vectorchildfinder.VectorDrawableCompat;`
its same on line 569 of maven.

**Comment by kfjohnny2** [comment]
Oh, thank you, dude! I was importing from "android.support.graphics.drawable.VectorDrawableCompat". My bad!
